### ISSUE TITLE
Remove local variable "proxy" in "noProxy" modifier

### ISSUE THREAD

**Issue by PaulRBerg** [PaulRBerg/prb-proxy#153]
This is @IaroslavMazur's suggestion:

> the initialization of a local `IPRBProxy` variable could be ditched for the direct access of the `Proxy` contract from storage. While the invalid calls would, indeed, need to access the storage twice in this case, the valid ones would become more efficient.

The reference is for the `noProxy` modifier defined here:

https://github.com/PaulRBerg/prb-proxy/blob/82d14b9d0b0f6be3df43268c41cffec4701368f8/src/PRBProxyRegistry.sol#L61-L67

However, we need to double-check if this would actually result in a gas optimization - it might be the case that, due to via IR, the gas cost is the same.

**Comment by PaulRBerg** [comment]
I made a gas comparison by using the same technique as the one described [here](https://github.com/PaulRBerg/prb-proxy/issues/154#issuecomment-1627613306).

Breakdown (for deploying proxies via the `deploy` function):

| Tx | Gas Cost |
|--------|--------|
| [With local variable](https://goerli.etherscan.io/tx/0x0263083b9e31e49fa393526301ee3ed519068307c56ccb1fa9a777cd2a6f758a) | 425,154 |
|[Without local variable](https://goerli.etherscan.io/tx/0x4d56213e3af2e816b2175bb7441bacf21dcab49b1c3572974e1c776e60f5ac72) | 425,214 |

Thus, again contrary to our expectations, removing the local variable `proxy` <ins>increases</ins> the gas cost - it does not decrease it. [Via IR is strange](https://twitter.com/PaulRBerg/status/1660262738709413888).

**Comment by IaroslavMazur** [comment]
> I made a gas comparison by using the same technique as the one described [here](https://github.com/PaulRBerg/prb-proxy/issues/154#issuecomment-1627613306).
> 
> Breakdown (for deploying proxies via the `deploy` function):
> 
> Tx	Gas Cost
> [With local variable](https://goerli.etherscan.io/tx/0x0263083b9e31e49fa393526301ee3ed519068307c56ccb1fa9a777cd2a6f758a)	425,154
> [Without local variable](https://goerli.etherscan.io/tx/0x4d56213e3af2e816b2175bb7441bacf21dcab49b1c3572974e1c776e60f5ac72)	425,214
> Thus, again contrary to our expectations, removing the local variable `proxy` increases the gas cost - it does not decrease it. [Via IR is strange](https://twitter.com/PaulRBerg/status/1660262738709413888).

As I can see, the definitions of the `noProxy` modifier are the same in both of the instances of `PRBProxyRegistry`:
![image](https://github.com/PaulRBerg/prb-proxy/assets/22785348/c091fcd7-b936-4e7e-abf7-be7cff565433)

![image](https://github.com/PaulRBerg/prb-proxy/assets/22785348/d8fca3d8-35d7-4825-8302-62ee14d41eae)

So, whatever is different about those 2 contracts (which is causing the different tx gas cost), it's not the `noProxy` modifier... 🤔

**Comment by PaulRBerg** [comment]
Sorry @IaroslavMazur - I've linked the incorrect tx above (for "Without local variable"). The correct deployment transaction is this:

https://goerli.etherscan.io/tx/0x3760410599dcbd15e12d119d96f8d0c5e189e9a5f4a7b81b0185522f8b3f3677

And the correct address for the adjusted registry is this:

https://goerli.etherscan.io/address/0xc3d1039afbb4a511ee9188725abf437fa748fa72

As you can see, the modifier in this contract is this:

```solidity
modifier noProxy(address owner) {
    if (address(_proxies[owner]) != address(0)) {
        revert PRBProxyRegistry_OwnerHasProxy(owner, _proxies[owner]);
    }
    _;
}
```

I'll let you close the issue once you double-check the updated URLs.

**Comment by IaroslavMazur** [comment]
Thank you for the clarification, @PaulRBerg!

I'm closing the issue.
