### ISSUE TITLE
Declare "method" outside of the loop in "uninstallPlugin"

### ISSUE THREAD

**Issue by PaulRBerg** [PaulRBerg/prb-proxy#154]
This is @IaroslavMazur's suggestion:

> it should be more efficient to declare `method` outside the for loop. Possibly, even with `--via-ir`.

The reference is for the `method` variable declaration here:

https://github.com/PaulRBerg/prb-proxy/blob/27594d50f049330c5acfa6cf45448152a2932ecf/src/PRBProxyRegistry.sol#L264

**Comment by PaulRBerg** [comment]
I tested this now. What I did:

- Deploy the [basic plugin](https://goerli.etherscan.io/address/0xfF2a2DA1f25658c7Cb5Cf08c0d4BB259e96cA972) (which has two methods) to Goerli
- Install the basic plugin on a proxy using the current version of the registry (the one with `method` defined within the loop)
- Define an adjusted version of `PRBProxyRegistry` with the `method` defined outside the loop (as suggested by @IaroslavMazur)
    - Note: I enabled the `optimized` profile when deploying
- Deploy the adjusted registry to Goerli
- Install the basic plugin on a proxy using the adjusted version of the registry

Breakdown:

| Tx | Gas Cost |
|--------|--------|
| [Inside the Loop](https://goerli.etherscan.io/tx/0x3ab91411fe32e1427bbb341d2d882efe86dd3ef79bfc0ab3a0eb1c5a29d908c4) |122,310 |
|[Outside the Loop](https://goerli.etherscan.io/tx/0x4d56213e3af2e816b2175bb7441bacf21dcab49b1c3572974e1c776e60f5ac72) | 122,358 |

Thus, contrary to our expectations, it turns out that declaring `method` outside the loop increases the cost. And the reason for this is via IR - I've started this [Twitter discussion](https://twitter.com/PaulRBerg/status/1660262738709413888) about how surprising via IR can be.

**Comment by IaroslavMazur** [comment]
> Thus, contrary to our expectations, declaring `method` outside the loop increases the cost. And the reason for this is via IR[here](https://twitter.com/PaulRBerg/status/1660262738709413888).

How very weird, indeed! 🤔 

Thank you for diving into this!
