### ISSUE TITLE
Weird behavior of `vm.expectRevert()` in runPlugin.t.sol

### ISSUE THREAD

**Issue by IaroslavMazur** [PaulRBerg/prb-proxy#162]
Because of an issue identified in `prb-proxy/test/proxy/run-plugin/runPlugin.t.sol`, the underlying contract functionality can’t be properly tested. The issue is that, for some reason, the `vm.expectRevert()` in the `test_RevertWhen_Error_…` functions doesn’t seem to care what argument is being passed to it - resulting in the respective tests succeeding anyways.

Here's a not-exhaustive list of examples that can be used to reproduce the problem:
 

```solidity
function test_RevertWhen_Error_Require() external whenPluginInstalled whenDelegateCallReverts {
        registry.installPlugin(plugins.reverter);
        vm.expectRevert(IPRBProxy.PRBProxy_PluginReverted.selector);
        (bool success,) = address(proxy).call(abi.encodeWithSelector(plugins.reverter.withRequire.selector));
        success;
    }
```

```solidity
function test_RevertWhen_Error_ReasonString() external whenPluginInstalled whenDelegateCallReverts {
        registry.installPlugin(plugins.reverter);
        vm.expectRevert();
        (bool success,) = address(proxy).call(abi.encodeWithSelector(plugins.reverter.withReasonString.selector));
        success;
    }
```

**Comment by PaulRBerg** [comment]
Oh, LOL - I know what's going on here: [`vm.expectRevert` does not work with low-level calls](https://twitter.com/PaulRBerg/status/1636724140282462215).

**Comment by IaroslavMazur** [comment]
> Oh, LOL - I know what's going on here: [`vm.expectRevert` does not work with low-level calls](https://twitter.com/PaulRBerg/status/1636724140282462215).

Great finding!

Now, the affected tests need to be adapted to the "no-expectRevert" approach, right?

**Comment by PaulRBerg** [comment]
> The affected tests need to be adapted to the "no-expectRevert" approach, right?

Yes.

We still need to use the low-level calls because Solidity would otherwise complain that the proxy does not implement the plugin methods. Therefore, the solution is to manually check the response status, and the return data, like this:

```solidity
function test_RevertWhen_Error_ReasonString() external whenPluginInstalled whenDelegateCallReverts {
    registry.installPlugin(plugins.reverter);
    (bool success, bytes memory actualResponse) =
        address(proxy).call(abi.encodeWithSelector(plugins.reverter.withReasonString.selector));
    assertFalse(success, "reverter.withReasonString did not revert");
    bytes memory expectedResponse = abi.encodeWithSelector(0x08c379a0, "You shall not pass");
    assertEq(actualResponse, expectedResponse, "You shall not pass reverter.withReasonString response mismatch");
}
```

Where `ERROR_STRING_SELECTOR` is defined like this:

```solidity
bytes4 internal constant ERROR_STRING_SELECTOR = bytes4(keccak256("Error(string)"));
```

Docs references:

- https://docs.soliditylang.org/en/v0.8.19/control-structures.html#revert
- https://docs.soliditylang.org/en/v0.8.19/control-structures.html#panic-via-assert-and-error-via-require

**Comment by IaroslavMazur** [comment]
> > The affected tests need to be adapted to the "no-expectRevert" approach, right?
> 
> Yes.
> 
> We still need to use the low-level calls because Solidity would otherwise complain that the proxy does not implement the plugin methods. Therefore, the solution is to manually check the response status, and the return data, like this:
> 
> ```solidity
> function test_RevertWhen_Error_ReasonString() external whenPluginInstalled whenDelegateCallReverts {
>     registry.installPlugin(plugins.reverter);
>     (bool success, bytes memory actualResponse) =
>         address(proxy).call(abi.encodeWithSelector(plugins.reverter.withReasonString.selector));
>     assertFalse(success, "reverter.withReasonString did not revert");
>     bytes memory expectedResponse = abi.encodeWithSelector(0x08c379a0, "You shall not pass");
>     assertEq(actualResponse, expectedResponse, "reverter.withReasonString response mismatch");
> }
> ```
> 
> Where `ERROR_STRING_SELECTOR` is defined like this:
> 
> ```solidity
> bytes4 internal constant ERROR_STRING_SELECTOR = bytes4(keccak256("Error(string)"));
> ```
> 
> Docs references:
> 
> * https://docs.soliditylang.org/en/v0.8.19/control-structures.html#revert
> * https://docs.soliditylang.org/en/v0.8.19/control-structures.html#panic-via-assert-and-error-via-require

Alright, sounds good!
