### ISSUE TITLE
Delete the "setMinGasReserve" function

### ISSUE THREAD

**Issue by PaulRBerg** [PaulRBerg/prb-proxy#21]
As explained in the README, the role of the `minGasReserve` storage variable is to prevent the proxy from becoming unusable if the EVM opcode gas costs change in the future.

But gas costs rarely change, and when they do, it is announced in advance. Thus I don't think it is warranted to keep the `setMinGasReserve` function in the proxy. An external target contract could be used to modify the value of the `minGasReserve` variable.

**Comment by cleanunicorn** [comment]
I would probably go even further and make `minGasReserve` immutable.

**Comment by paulrberg** [comment]
> I would probably go even further and make `minGasReserve` immutable.

Nah .. as per the README:

> ...
> A minimum gas reserve is saved in storage such that the proxy does not become unusable if EVM opcode gas costs change in the future.

The added gas cost for making the variable mutable is worth it. It prevents a scenario whereby all PRBProxies are effectively dead.
