### ISSUE TITLE
Add support for Optimism

### ISSUE THREAD

**Issue by paulrberg** [paulrberg/prb-proxy#33]
Gotta find a workaround for this: https://github.com/Zoltu/deterministic-deployment-proxy/issues/7.

**Comment by gakonst** [comment]
no workaround required for arbitrum rn I believe https://github.com/Zoltu/deterministic-deployment-proxy/issues/7#issuecomment-1129407585

**Comment by paulrberg** [comment]
@gakonst thanks for the heads-up! Hopefully the deployment proxy will become available on Optimism too.

**Comment by smartcontracts** [comment]
@paulrberg it's deployed to Optimism

**Comment by gakonst** [comment]
https://github.com/ethereum-optimism/optimism/issues/1883
