### ISSUE TITLE
Slot 0 could be clobbered in a target contract

### ISSUE THREAD

**Issue by ElmoArmy** [PaulRBerg/prb-proxy#86]
Hey @PaulRBerg, thanks for sharing this project as well as others with the world. Wanted to bring this issue of storage slots to your attention in case it had not been considered during implementation. I may also be missing some mechanism or design decision that makes this irrelevant. 

According to this:
https://github.com/PaulRBerg/prb-proxy/blob/dab260932a24c83f9c978b6e83e15ab4b9877c6d/src/abstracts/PRBProxyStorage.sol#L11

The owner variable is being assigned to the default layout slot ( 0 in this case) and authors of target contracts would have to be careful not to use the same slot in their contract which could lead to unexpected behavior or at worst proxy account takeover. While target contracts have a lot of power and should be reviewed before calling into them, mitigating this issue from the proxy contract would be an improvement and prevent accidents / sneaky attempts to trick proxy users. 

Possible solutions 
- [EIP-1967](https://eips.ethereum.org/EIPS/eip-1967) / [Diamond Storage Pattern
](https://dev.to/mudgen/how-diamond-storage-works-90e)
- [EIP-1822](https://eips.ethereum.org/EIPS/eip-1822)
- Classify as a known/non issue, the proxy owner must trust/verify that target contracts won't maliciously affect contract state storage.

**Comment by PaulRBerg** [comment]
Hi @ElmoArmy, thank you for your issue.

There is a check to prevent transfer of ownership on this line:

https://github.com/PaulRBerg/prb-proxy/blob/dab260932a24c83f9c978b6e83e15ab4b9877c6d/src/PRBProxy.sol#L145-L147

And there is a test written for this:

https://github.com/PaulRBerg/prb-proxy/blob/dab260932a24c83f9c978b6e83e15ab4b9877c6d/test/proxy/execute/execute.t.sol#L82

So it is not possible to change the owner of a proxy - regardless of one's intentions (good, or bad).

**Comment by ElmoArmy** [comment]
> Hi @ElmoArmy, thank you for your issue.
> 
> There is a check to prevent transfer of ownership on this line:
> 
> https://github.com/PaulRBerg/prb-proxy/blob/dab260932a24c83f9c978b6e83e15ab4b9877c6d/src/PRBProxy.sol#L145-L147
> 
> And there is a test written for this:
> 
> https://github.com/PaulRBerg/prb-proxy/blob/dab260932a24c83f9c978b6e83e15ab4b9877c6d/test/proxy/execute/execute.t.sol#L82
> 
> So it is not possible to change the owner of a proxy - regardless of one's intentions (good, or bad).

Oh I missed that and yea I can see that takes care of the proxy takeover issue.

`minGasReserve` doesn't seem to have a similar protection. Overriding slot1 with a large value could brick the execution calls, no?

**Comment by PaulRBerg** [comment]
Yes, but there are all kinds of bad things that can happen if given access to a malicious party. It is impossible to prevent all possible harms that can be done - users have to be careful.
